apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iisa-scores-cache
  namespace: subgraph-dips-indexer-selection-iisa-daily-cronjob-samuel
  labels:
    app: iisa
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
