apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iisa-scores
  namespace: subgraph-dips-indexer-selection-iisa-daily-cronjob-samuel
  labels:
    app: iisa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
