apiVersion: v1
kind: Service
metadata:
  name: iisa
  labels:
    app: iisa
spec:
  type: ClusterIP
  selector:
    app: iisa
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
