# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_queries.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'gateway_queries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gateway_queries.proto\"\xe3\x02\n\x13\x43lientQueryProtobuf\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x16\n\x0ereceipt_signer\x18\x02 \x01(\x0c\x12\x10\n\x08query_id\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\x12\x0e\n\x06result\x18\x05 \x01(\t\x12\x18\n\x10response_time_ms\x18\x06 \x01(\r\x12\x15\n\rrequest_bytes\x18\x07 \x01(\r\x12\x1b\n\x0eresponse_bytes\x18\x08 \x01(\rH\x00\x88\x01\x01\x12\x16\n\x0etotal_fees_usd\x18\t \x01(\x01\x12.\n\x0findexer_queries\x18\n \x03(\x0b\x32\x15.IndexerQueryProtobuf\x12\x14\n\x07user_id\x18\x0b \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08subgraph\x18\x0c \x01(\tH\x02\x88\x01\x01\x42\x11\n\x0f_response_bytesB\n\n\x08_user_idB\x0b\n\t_subgraph\"\xf5\x01\n\x14IndexerQueryProtobuf\x12\x0f\n\x07indexer\x18\x01 \x01(\x0c\x12\x12\n\ndeployment\x18\x02 \x01(\x0c\x12\x12\n\nallocation\x18\x03 \x01(\x0c\x12\x15\n\rindexed_chain\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x0f\n\x07\x66\x65\x65_grt\x18\x06 \x01(\x01\x12\x18\n\x10response_time_ms\x18\x07 \x01(\r\x12\x16\n\x0eseconds_behind\x18\x08 \x01(\r\x12\x0e\n\x06result\x18\t \x01(\t\x12\x16\n\x0eindexer_errors\x18\n \x01(\t\x12\x15\n\rblocks_behind\x18\x0b \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_queries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTQUERYPROTOBUF']._serialized_start=26
  _globals['_CLIENTQUERYPROTOBUF']._serialized_end=381
  _globals['_INDEXERQUERYPROTOBUF']._serialized_start=384
  _globals['_INDEXERQUERYPROTOBUF']._serialized_end=629
# @@protoc_insertion_point(module_scope)
